packages:
  - playground
  - packages/*

catalogs:
  build:
    sass: ^1.102.0

  peer:
    bytemd: ^1.22.0

  prod:
    '@primer/css': ^15.2.0
    '@primer/primitives': ^11.10.0
    '@tofrankie/github-markdown-css': ^0.0.5
